name: bismart_flutter
description: "Bi'S MART - Hệ thống quản lý chuỗi cửa hàng dinh dưỡng"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # HTTP & API
  dio: ^5.4.3

  # Charts (Bar chart, Line chart)
  fl_chart: ^0.66.2

  # Calendar
  table_calendar: ^3.0.9

  # Local storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.5

  # Video player (anti-piracy lesson playback)
  video_player: ^2.9.1
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
